window.EXTRAS = {
  exec: [
    "column","bar","grouped_bar","lollipop","ordered_bar","dot_plot","bullet",
    "slope","dumbbell","diverging_bar","line","multiline","area","stacked_bar",
    "stacked100","pie","donut","waffle","waterfall","funnel","heatmap",
    "sparkline","gantt","timeline","pareto","treemap","step"
  ],
  news: [
    "column","bar","grouped_bar","lollipop","ordered_bar","dot_plot","bullet",
    "slope","dumbbell","diverging_bar","line","multiline","area","stacked_bar",
    "stacked100","pie","donut","waffle","waterfall","funnel","heatmap",
    "sparkline","gantt","timeline","pareto","treemap","step",
    "choropleth","bubble_map","pictogram","bump","butterfly","surplus_deficit",
    "calendar_heatmap","sankey","connected_scatter","population_pyramid",
    "proportional_area","span"
  ],

  tree: [
    {
      id: "one_num",
      ar: "متغيّر كمّي واحد",
      en: "One numeric variable",
      hint_ar: "درجات، أعمار، أزمنة استجابة — توزيع قيمة واحدة.",
      hint_en: "Scores, ages, response times — the shape of one value.",
      rec: ["histogram","density","boxplot","violin"],
      avoid: "bar",
      avoid_ar: "العمود للفئات لا للمتصل. لا تقطع المتغير إلى صناديق اعتباطية ثم ترسمه أعمدة.",
      avoid_en: "Bars are for categories. Don't bin a continuous variable then treat the bins as a bar chart of names."
    },
    {
      id: "two_num",
      ar: "متغيّران كمّيان",
      en: "Two numeric variables",
      hint_ar: "علاقة، عنقود، شذوذ بين X و Y.",
      hint_en: "Relationship, clusters, outliers between X and Y.",
      rec: ["scatter","hexbin","density2d","bubble"],
      avoid: "line",
      avoid_ar: "الخط يوحي بزمن أو ترتيب. لا تصل نقاط العلاقة بخط إلا إذا كان المحور زمناً.",
      avoid_en: "A line implies sequence or time. Don't connect relationship dots unless X is ordered time."
    },
    {
      id: "cat_num",
      ar: "فئات + قيمة",
      en: "Categories + a value",
      hint_ar: "مبيعات حسب المنطقة، رضا حسب المنتج.",
      hint_en: "Sales by region, satisfaction by product.",
      rec: ["bar","lollipop","ordered_bar","dot_plot"],
      avoid: "pie",
      avoid_ar: "الدائرة تفشل بعد 5 فئات أو حين تريد ترتيباً دقيقاً.",
      avoid_en: "Pies fail past ~5 slices, or whenever ranking must be precise."
    },
    {
      id: "time",
      ar: "سلسلة زمنية",
      en: "Time series",
      hint_ar: "اتجاه، موسمية، انكسار عبر أسابيع أو سنوات.",
      hint_en: "Trend, seasonality, breaks across weeks or years.",
      rec: ["line","multiline","area","slope"],
      avoid: "pie",
      avoid_ar: "دائرة لكل سنة ليست سلسلة زمنية. هي كتيب إعلانات.",
      avoid_en: "A pie per year is not a time series. It is a brochure."
    },
    {
      id: "part",
      ar: "أجزاء من كلّ",
      en: "Parts of a whole",
      hint_ar: "حصص تُجمع إلى 100٪.",
      hint_en: "Shares that add to 100%.",
      rec: ["stacked100","waffle","donut","treemap"],
      avoid: "pie",
      avoid_ar: "الدائرة مسموحة لـ 2–4 شرائح فقط. الوافل أو المكدّس 100٪ أصدق.",
      avoid_en: "A pie is tolerable for 2–4 slices. A waffle or 100% stacked bar is more honest."
    },
    {
      id: "geo",
      ar: "بيانات جغرافية",
      en: "Geographic data",
      hint_ar: "معدّل أو عدد مرتبط بمكان.",
      hint_en: "A rate or a count tied to a place.",
      rec: ["choropleth","bubble_map","dot_density","connection_map"],
      avoid: "choropleth",
      avoid_ar: "لا تلوّن المجاميع المطلقة. Choropleth للمعدّلات فقط. للمجاميع: فقاعات.",
      avoid_en: "Don't colour raw counts. Choropleth is for rates. Use bubbles for totals."
    },
    {
      id: "flow",
      ar: "تدفق أو شبكة",
      en: "Flow or network",
      hint_ar: "من → إلى، أو علاقات بين كيانات.",
      hint_en: "From → to, or relationships among entities.",
      rec: ["sankey","alluvial","network","arc"],
      avoid: "chord",
      avoid_ar: "الوتر جميل ونادر الصدق في قراءة الرقم. Sankey أوضح للتدفق.",
      avoid_en: "Chords are pretty and rarely honest about magnitude. Sankey is clearer for flow."
    },
    {
      id: "hier",
      ar: "هرمية",
      en: "Hierarchy",
      hint_ar: "أب–ابن: ميزانية، ملفات، تصنيفات.",
      hint_en: "Parent–child: budgets, files, taxonomies.",
      rec: ["treemap","sunburst","icicle","dendrogram"],
      avoid: "pie",
      avoid_ar: "دائرة متعددة المستويات تُقرأ كزينة. Treemap أو Sunburst للحجم والمستوى.",
      avoid_en: "A multi-level pie reads as decoration. Treemap or sunburst carry size and level."
    }
  ],

  play: [
    { id: "pie", ar: "دائرة 2025", en: "Pie 2025",
      story_ar: "الجوال يبدو البطل. لا نرى أن المتجر كان الأكبر قبل خمس سنوات.",
      story_en: "Mobile looks like the hero. You cannot see that Store used to lead.",
      verdict: "weak" },
    { id: "donut", ar: "دونات 2025", en: "Donut 2025",
      story_ar: "نفس فخ الدائرة، مع رقم في الوسط. الحصّة اللحظية لا الاتجاه.",
      story_en: "Same trap as the pie, with a number in the hole. Snapshot, not trend.",
      verdict: "weak" },
    { id: "bar", ar: "أعمدة 2025", en: "Bars 2025",
      story_ar: "الترتيب واضح: جوال ثم متجر. ما زال السؤال الزمني غائباً.",
      story_en: "Ranking is clear: Mobile then Store. The time question is still unanswered.",
      verdict: "ok" },
    { id: "lollipop", ar: "مصّاصة 2025", en: "Lollipop 2025",
      story_ar: "نفس الأعمدة بحبر أقل. جيد للتقرير، أعمى عن التغيّر.",
      story_en: "Same as bars, less ink. Fine for a report, blind to change.",
      verdict: "ok" },
    { id: "grouped", ar: "أعمدة مجمّعة", en: "Grouped bars",
      story_ar: "كل سنة وكل قناة. دقيق ومتعِب. العين تقارن أربع مجموعات × ست سنوات.",
      story_en: "Every year, every channel. Precise and tiring. The eye juggles 4×6 bars.",
      verdict: "ok" },
    { id: "stacked", ar: "مكدّس بالإيراد", en: "Stacked (revenue)",
      story_ar: "السوق كبر والجوال يملأ النمو. المتجر لا يختفي بالإيراد كما يختفي بالحصّة.",
      story_en: "The market grew and Mobile filled the growth. Store does not vanish in revenue the way it does in share.",
      verdict: "good" },
    { id: "stacked100", ar: "مكدّس 100٪", en: "100% stacked",
      story_ar: "قصّة المزيج: الجوال يبتلع حصّة المتجر. الويب والباقي ثابتان.",
      story_en: "The mix story: Mobile eats Store's share. Web and Other stand still.",
      verdict: "good" },
    { id: "line", ar: "خطوط", en: "Lines",
      story_ar: "الاتجاه أوضح ما يكون: تقاطع الجوال والمتجر. الويب خط أفقي.",
      story_en: "Trend at its clearest: Mobile and Store cross. Web is a flat line.",
      verdict: "best" },
    { id: "slope", ar: "ميل 2020→2025", en: "Slope 2020→2025",
      story_ar: "جملة واحدة: من صعد ومن هبط. يخفي المسار بين النقطتين.",
      story_en: "One sentence: who rose, who fell. It hides the path between the two years.",
      verdict: "best" },
    { id: "area", ar: "مساحة مكدّسة", en: "Stacked area",
      story_ar: "ثِقل الحصص عبر الزمن. الطبقة الوسطى (المتجر) أصعب قراءة من الخط.",
      story_en: "The weight of shares over time. The middle layer (Store) is harder to read than a line.",
      verdict: "ok" },
    { id: "treemap", ar: "شجرة 2025", en: "Treemap 2025",
      story_ar: "مساحة = حصّة. جميل لملصق، أعمى عن التاريخ.",
      story_en: "Area = share. Nice on a poster, blind to history.",
      verdict: "weak" },
    { id: "waffle", ar: "وافل 2025", en: "Waffle 2025",
      story_ar: "كل مربع = 1٪. أسهل عدّاً من الدائرة، وما زال لقطة لسنة واحدة.",
      story_en: "Each square = 1%. Easier to count than a pie, still a one-year snapshot.",
      verdict: "ok" }
  ],

  quiz: [
    { id: "p01_question", n: "01",
      q_ar: "السؤال كان: أي قناة نمت؟ ما الخطأ في دائرة هذا العام؟",
      q_en: "The question was: which channel grew? What is wrong with this year's pie?",
      options_ar: ["الألوان غير متباينة","تجيب على الحصّة لا على النمو","ينقصها عنوان","الشرائح ليست 100٪"],
      options_en: ["Colours lack contrast","It answers share, not growth","It needs a title","Slices don't sum to 100%"],
      answer: 1 },
    { id: "p02_position", n: "02",
      q_ar: "لماذا تفشل الدائرة في نسب 26 / 25 / 25 / 24؟",
      q_en: "Why does the pie fail for shares 26 / 25 / 25 / 24?",
      options_ar: ["لأن الدائرة ثلاثية الأبعاد","لأن الزاوية أضعف من الموضع على محور","لأن الألوان متشابهة","لأن النسب لا تُجمع إلى 100"],
      options_en: ["Because it is 3D","Because angle is weaker than position on a shared axis","Because colours are similar","Because they don't add to 100"],
      answer: 1 },
    { id: "p03_maps", n: "03",
      q_ar: "تظليل الخريطة بعدد الحالات يجعل المنطقة الكبيرة تبدو الأسوأ. ما التصحيح؟",
      q_en: "Colouring the map by case counts makes the large region look worst. The fix?",
      options_ar: ["زيادة التباين","استخدام معدّل لكل سكّان","إزالة الحدود","تحويلها لثلاثي أبعاد"],
      options_en: ["Increase contrast","Use a rate per population","Remove borders","Make it 3D"],
      answer: 1 },
    { id: "p04_causation", n: "04",
      q_ar: "ارتباط 0.91 بين المثلجات والغرق. ما الجملة الصادقة؟",
      q_en: "r = 0.91 between ice cream and drownings. The honest sentence?",
      options_ar: ["المثلجات تسبّب الغرق","المتغيّر المختبئ هو الحر/الموسم","يجب حذف النقاط الشاذة","العيّنة صغيرة جداً"],
      options_en: ["Ice cream causes drowning","The lurking variable is heat/season","Outliers should be dropped","The sample is too small"],
      answer: 1 },
    { id: "p05_dualaxis", n: "05",
      q_ar: "إيرادات 100→103 تبدو كانفجار. من الفاعل؟",
      q_en: "Revenue 100→103 looks like an explosion. Who is acting?",
      options_ar: ["البيانات","المحور المضغوط (99–104)","لون الخط","عدد النقاط"],
      options_en: ["The data","The squeezed axis (99–104)","The line colour","The number of points"],
      answer: 1 },
    { id: "p06_color", n: "06",
      q_ar: "ما عيب خريطة حرارية بقوس قزح (jet)؟",
      q_en: "What is wrong with a rainbow (jet) heatmap?",
      options_ar: ["الجمال ناقص","حدود وهمية: الأصفر يبدو فئة لا قيمة","لا يمكن طباعتها","تحتاج أسطورة"],
      options_en: ["Not pretty enough","Fake cliffs: yellow looks like a category, not a value","Cannot be printed","Needs a legend"],
      answer: 1 },
    { id: "p07_decoration", n: "07",
      q_ar: "لماذا الأعمدة ثلاثية الأبعاد مضلّلة حتى لو الأرقام صحيحة؟",
      q_en: "Why are 3D bars misleading even when the numbers are right?",
      options_ar: ["لأنها قديمة","المنظور يسرق الارتفاع فتتغيّر المقارنة","لأن الظلال غامقة","لأنها تحتاج محوراً مزدوجاً"],
      options_en: ["They look dated","Perspective steals height, so comparison changes","Shadows are too dark","They need a dual axis"],
      answer: 1 },
    { id: "p08_uncertainty", n: "08",
      q_ar: "متوسطات 74 و73 و72 بلا عارضات على محور مقطوع. ما الكذبة؟",
      q_en: "Means of 74, 73, 72 with no error bars on a truncated axis. The lie?",
      options_ar: ["الألوان","اختراع فائز رغم تداخل فترات الثقة","ترتيب الأعمدة","حجم الخط"],
      options_en: ["The colours","Inventing a winner even though confidence intervals overlap","Bar order","Font size"],
      answer: 1 }
  ]
};

window.RECIPES = {
  default: {
    excel: "Insert → Chart، ثم أزل خطوط الشبكة الزائدة واكتب العنوان كجملة.",
    pbi: "Visualizations pane → اختر النوع → Fields. عطّل auto-legend إن كانت التسمية على الرسم أوضح.",
    py: "import matplotlib.pyplot as plt\nfig, ax = plt.subplots()\n# ax.bar / ax.plot / ax.scatter ...\nax.spines['top'].set_visible(False)\nax.spines['right'].set_visible(False)\nplt.show()"
  },
  column: { excel: "Insert → Column chart. ابدأ المحور من صفر. Data labels على الأعمدة لا أسطورة جانبية إن كانت فئة واحدة.", pbi: "Clustered column. Sort by value إن لم يكن للمحور ترتيب طبيعي.", py: "ax.bar(cats, vals, color='#2C6E7A')\nax.set_ylim(0, None)" },
  bar: { excel: "Insert → Bar chart. استخدمه للأسماء الطويلة. رتّب تنازلياً.", pbi: "Clustered bar + Sort by measure.", py: "ax.barh(cats, vals); ax.invert_yaxis()" },
  line: { excel: "Insert → Line. لا تصل فئات اسمية بخط. اترك الفجوات الزمنية مقطوعة.", pbi: "Line chart. Date hierarchy على المحور السيني.", py: "ax.plot(x, y, marker='o')\nax.set_ylim(0, None)  # إلا إذا كان الصفر غير معنى" },
  pie: { excel: "Insert → Pie فقط لـ 2–4 شرائح. الأفضل: Doughnut مع رقم في الوسط، أو Bar.", pbi: "Donut، وفضّل 100% stacked bar للمقارنة بين كليات.", py: "ax.pie(vals, labels=labs)  # تجنّبه إن أمكن؛ استخدم barh" },
  scatter: { excel: "Insert → Scatter. أضف Trendline بحذر ولا تكتب «يؤدي إلى».", pbi: "Scatter chart. Size اختياري للفقاعة.", py: "ax.scatter(x, y, alpha=0.75)\n# لا تستنتج سببية من np.polyfit" },
  choropleth: { excel: "Filled Map (Excel 365) — حصراً لمعدّل لا لمجموع.", pbi: "Shape map / Filled map. استخدم معدل لكل 100 ألف.", py: "geopandas.GeoDataFrame.plot(column='rate', cmap='Teal', legend=True)" },
  sankey: { excel: "ليس أصلياً. Power BI أو Python أو Flourish.", pbi: "Sankey visual من AppSource. Source / Destination / Weight.", py: "plotly.graph_objects.Sankey(node=..., link=dict(source=, target=, value=))" },
  boxplot: { excel: "Box & Whisker (Excel 365) أو حساب ربيعات يدوياً.", pbi: "غير أصلي؛ استخدم R visual أو Python visual.", py: "ax.boxplot(data, labels=groups)" },
  bullet: { excel: "عمود أفقي + خط هدف (scatter على محور ثانٍ) محاكاة لـ Few.", pbi: "Bullet chart custom visual، أو bar + constant line.", py: "ax.barh([0], value); ax.plot(target, 0, marker='|', ms=18)" },
  waterfall: { excel: "Insert → Waterfall. ميّز الإجمالي بلون مختلف.", pbi: "Waterfall built-in. Breakdown + Total.", py: "ax.bar(steps, heights, bottom=bottoms)  # أو plotly.graph_objects.Waterfall" },
  heatmap: { excel: "جدول + Conditional Formatting بتدرّج لوني واحد (لا قوس قزح).", pbi: "Matrix + background color scale (sequential).", py: "ax.imshow(M, cmap='YlGnBu'); plt.colorbar(ax.images[0])" }
};

window.PRIN_EN = {
    p01_question: {
      setup: "One dataset: channel shares in 2020 and 2025. The real question: which channel grew?",
      wrong: "The pie shows 2025 shares only. Mobile looks like the hero, but the chart never says whether it grew or was already large.",
      right: "The slope puts 2020 against 2025 for every channel. The sentence completes: Mobile rose, Store fell, Web and Other stood still.",
      rule: "Before picking a shape, finish: “I want the reader to see that…”. If you cannot, do not draw yet."
    },
    p02_position: {
      setup: "Four regions at 26, 25, 25, 24. The difference is real, and small.",
      wrong: "The pie encodes share as angle and area. The eye cannot split 26 from 24 without the labels doing the work.",
      right: "Horizontal bars encode value as position on a shared axis. Ranking is immediate.",
      rule: "For precise comparison: position on a shared axis > bar length > angle > area > colour."
    },
    p03_maps: {
      setup: "Six regions. The large ones have many people and many cases. The small ones have higher rates.",
      wrong: "Colouring by counts makes the largest region look worst. The map measures population size, not risk.",
      right: "Same borders, coloured by rate. The story flips: R3 and R4 are the hotspots.",
      rule: "Choropleth is for rates. For absolute counts: bubbles or numbers, not area fills."
    },
    p04_causation: {
      setup: "Ice-cream sales and drownings over 12 months. r ≈ 0.91.",
      wrong: "A scatter with a trend line and a mental caption: ice cream causes drowning. The dots are true; the implication is not.",
      right: "Both series with temperature by month. All three rise in summer. Heat is the lurking variable.",
      rule: "Without a causal design, write “moves with”, not “leads to”. Hunt the third variable."
    },
    p05_dualaxis: {
      setup: "Revenue moves 100→103. Users move 12→98. Two different stories.",
      wrong: "A squeezed left axis (99–104) makes revenue look as if it tracks the user explosion. The scale is the actor.",
      right: "Revenue on a zero-based axis: almost flat. Users on their own panel, where growth is real.",
      rule: "Dual axes can make any two series look synchronised. Prefer two charts, or one derived metric."
    },
    p06_color: {
      setup: "The same weekly activity matrix. Only the colour scale changes.",
      wrong: "Rainbow (jet): yellow and green look like different categories. Fake cliffs appear where change is gradual.",
      right: "A sequential single-hue scale. Light is low, dark is high. Quantity is the only message.",
      rule: "One series = one colour. Quantity = sequential. Deviation = diverging. Rainbow is banned for magnitudes."
    },
    p07_decoration: {
      setup: "Four values: 42, 55, 48, 51. B is the highest if you leave it to position.",
      wrong: "3D bars. Perspective steals height: C looks shorter than it is. Theatre without information.",
      right: "2D bars from zero, values on the bars. B leads; the rest are close, without fake drama.",
      rule: "Tufte: raise the share of ink that carries data. 3D, glow, clip-art = a tax."
    },
    p08_uncertainty: {
      setup: "Four methods with means 74.0, 73.2, 72.1, 71.4, each CI about ±4.",
      wrong: "Ranked bars on a truncated axis (68–76) with no whiskers. B “wins” as if the race is over.",
      right: "The same means from zero, with 95% CIs. Every interval overlaps. There is no winner worth claiming.",
      rule: "A mean without spread in a scientific setting is a false claim of precision."
    }
};

window.I18N = {
  ar: {
    brand: "أطلس المفردات البصرية",
    nav_home: "الرئيسية",
    nav_choose: "الغرض",
    nav_data: "البيانات",
    nav_gallery: "المعرض",
    nav_play: "نفس البيانات",
    nav_quiz: "تحقيق",
    nav_compare: "قارن",
    nav_principles: "المبادئ",
    nav_poster: "ملصق",
    nav_sources: "المصادر",
    search: "ابحث عن رسم…",
    tools: "أدوات",
    audience: "الجمهور",
    aud_all: "محلل — الكل",
    aud_news: "صحفي",
    aud_exec: "تنفيذي",
    cb: "محاكاة عمى الألوان",
    cb_off: "ألوان أصلية",
    cb_on: "deuteranopia",
    lang: "EN",
    hero_lead: "دليل تفاعلي لاختيار الرسم: 80 نوعاً، شجرة بيانات، وورشة «نفس الأرقام × 12 شكلاً». ابدأ من السؤال لا من الشكل.",
    cta_choose: "ماذا تريد أن تُظهر؟",
    cta_data: "ماذا عندك في الجدول؟",
    cta_quiz: "اكشف التضليل",
    steps_t: "ثلاث خطوات قبل أي رسم",
    fam_t: "العائلات العشر",
    fam_s: "التصنيف حسب الغرض، بمنطق Financial Times Visual Vocabulary.",
    prin_t: "مبادئ لا تُساوَم",
    prin_s: "اضغط مبدأ لترى نفس البيانات مضلّلة ثم صادقة.",
    tools_t: "الورشة",
    tools_s: "شجرة البيانات، نفس الأرقام باثني عشر شكلاً، تحقيق الجرائم البصرية، مقارنة رسمين، ملصق الجدار.",
    when: "متى تستخدمه",
    avoid: "متى تتجنّبه",
    data: "البيانات المطلوبة",
    mistake: "خطأ شائع",
    alt: "بديل أفضل أحياناً",
    family: "العائلة",
    recipe: "كيف تُصنعه",
    rec_card: "بطاقة التوصية",
    copy: "نسخ النص",
    download: "تنزيل البطاقة",
    copied: "تم النسخ",
    start: "ابدأ بـ",
    avoid_short: "تجنّب",
    rec_charts: "رسوم مرشّحة",
    forbid: "لا تستخدم",
    story: "القصة التي يرويها هذا الشكل",
    verdict_best: "الأصدق لهذا السؤال",
    verdict_good: "جيد",
    verdict_ok: "مقبول",
    verdict_weak: "يُضلّل السؤال الزمني",
    quiz_title: "تحقيق الجرائم البصرية",
    quiz_sub: "ثماني تهم. اختر سبب التضليل قبل كشف الجواب.",
    quiz_next: "التالي",
    quiz_again: "أعد التحقيق",
    quiz_score: "النتيجة",
    check: "تحقّق",
    correct: "صحيح",
    wrong: "لا — انظر المبدأ",
    compare_t: "قارن رسمين",
    compare_s: "نفس الصفحة، عقدان مختلفان. مفيد حين يختلف الفريق.",
    poster_t: "ملصق المفردات البصرية",
    poster_s: "طبعة A3 بجانب الشاشة. ملف → طباعة → حجم A3، هوامش ضيقة.",
    print: "طباعة الملصق",
    footer: "تحرير عربي بمعيار FT Visual Vocabulary و From Data to Viz",
    choose_t: "ماذا تريد أن تُظهر؟",
    choose_s: "اختر الهدف. تظهر التوصية وما الذي يضلّل، ثم معرض العائلة.",
    data_t: "ماذا عندك في الجدول؟",
    data_s: "شكل البيانات أولاً، ثم الرسم. هذا مسار From Data to Viz.",
    play_t: "نفس البيانات × 12 شكلاً",
    play_s: "حصص أربع قنوات من 2020 إلى 2025. بدّل الشكل واقرأ الجملة التي يفرضها.",
    gallery_t: "كل الرسوم",
    all_charts_of: "كل رسوم",
    empty: "لا نتائج.",
    both: "الاثنان",
    misleading: "مضلّل فقط",
    honest: "صادق فقط",
    why_bad: "لماذا هذا مضلّل",
    why_good: "لماذا هذا صادق",
    rule: "القاعدة",
    vs: "مقابل"
  },
  en: {
    brand: "Visual Vocabulary Atlas",
    nav_home: "Home",
    nav_choose: "Purpose",
    nav_data: "Data shape",
    nav_gallery: "Gallery",
    nav_play: "Same data",
    nav_quiz: "Chart crimes",
    nav_compare: "Compare",
    nav_principles: "Principles",
    nav_poster: "Poster",
    nav_sources: "Sources",
    search: "Search a chart…",
    tools: "Tools",
    audience: "Audience",
    aud_all: "Analyst — all",
    aud_news: "Journalist",
    aud_exec: "Executive",
    cb: "Colour-blind sim",
    cb_off: "Original",
    cb_on: "deuteranopia",
    lang: "ع",
    hero_lead: "An interactive chart-chooser: 80 types, a data-shape tree, and a studio that redraws one dataset twelve ways. Start from the sentence, not the shape.",
    cta_choose: "What do you want to show?",
    cta_data: "What is in the table?",
    cta_quiz: "Spot the lie",
    steps_t: "Three steps before any chart",
    fam_t: "Ten families",
    fam_s: "Classified by purpose, after the Financial Times Visual Vocabulary.",
    prin_t: "Non-negotiable principles",
    prin_s: "Open a principle to see the same data drawn dishonestly, then honestly.",
    tools_t: "The studio",
    tools_s: "Data-shape tree, one dataset × 12 shapes, chart-crime quiz, compare two charts, wall poster.",
    when: "When to use",
    avoid: "When to avoid",
    data: "Data needed",
    mistake: "Common mistake",
    alt: "Often better",
    family: "Family",
    recipe: "How to make it",
    rec_card: "Recommendation card",
    copy: "Copy text",
    download: "Download card",
    copied: "Copied",
    start: "Start with",
    avoid_short: "Avoid",
    rec_charts: "Recommended",
    forbid: "Do not use",
    story: "The sentence this shape forces",
    verdict_best: "Most honest for this question",
    verdict_good: "Good",
    verdict_ok: "Acceptable",
    verdict_weak: "Misleads the time question",
    quiz_title: "Chart-crime desk",
    quiz_sub: "Eight charges. Pick why it lies before the reveal.",
    quiz_next: "Next",
    quiz_again: "Retry the case",
    quiz_score: "Score",
    check: "Check",
    correct: "Correct",
    wrong: "No — see the principle",
    compare_t: "Compare two charts",
    compare_s: "One page, two contracts with the reader. Useful when a team disagrees.",
    poster_t: "Visual vocabulary poster",
    poster_s: "Print A3 beside the screen. File → Print → A3, narrow margins.",
    print: "Print poster",
    footer: "Arabic edition after FT Visual Vocabulary and From Data to Viz",
    choose_t: "What do you want to show?",
    choose_s: "Pick the goal. See what to start with, what usually lies, then the family gallery.",
    data_t: "What is in the table?",
    data_s: "Data shape first, then the chart. The From Data to Viz path.",
    play_t: "Same data × 12 shapes",
    play_s: "Four channel shares, 2020–2025. Switch the shape and read the sentence it imposes.",
    gallery_t: "All charts",
    all_charts_of: "All charts in",
    empty: "No results.",
    both: "Both",
    misleading: "Misleading",
    honest: "Honest",
    why_bad: "Why this misleads",
    why_good: "Why this is honest",
    rule: "The rule",
    vs: "vs"
  }
};
